# Generated by Django 3.2.2 on 2021-05-13 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(default='', max_length=155, null=True)),
                ('age', models.CharField(default='', max_length=155, null=True)),
                ('comment', models.CharField(default='', max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenom', models.CharField(max_length=155, null=True)),
                ('nom', models.CharField(default='', max_length=155, null=True)),
                ('adresse', models.CharField(default='', max_length=155, null=True)),
                ('num', models.CharField(default='', max_length=255, null=True)),
                ('mail', models.CharField(default='', max_length=255, null=True)),
                ('profession', models.CharField(max_length=155, null=True)),
                ('comment', models.CharField(max_length=155, null=True)),
                ('chien', models.ManyToManyField(default='', null=True, to='management.Chien')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenom', models.CharField(max_length=155, null=True)),
                ('nom', models.CharField(default='', max_length=155, null=True)),
                ('adresse', models.CharField(default='', max_length=155, null=True)),
                ('num', models.CharField(default='', max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('race', models.CharField(default='', max_length=155, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(default='', max_length=255, null=True)),
                ('prix', models.DecimalField(decimal_places=2, default='', max_digits=6, null=True)),
                ('race', models.CharField(choices=[('Petite', 'Petit'), ('Moyenne', 'Moyen'), ('Grande', 'Grand')], default='Moyenne', max_length=9)),
                ('duree', models.CharField(choices=[('~ 5 min.', '5'), ('~ 30 min.', '30'), ('~ 1h00', '60'), ('~ 1h30', '90'), ('~ 2h00', '120'), ('~ 2h +', '+120')], default='~ 30 min.', max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='RDV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('completed', models.DateTimeField(null=True)),
                ('comment', models.TextField(default='', max_length=255, null=True)),
                ('client', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.client')),
                ('service', models.ManyToManyField(default='', null=True, to='management.Service')),
                ('toiletteur', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.employee')),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='toiletteur',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.employee'),
        ),
        migrations.AddField(
            model_name='chien',
            name='race',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.race'),
        ),
    ]
