# Generated by Django 3.2.2 on 2021-05-06 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenom', models.CharField(max_length=155, null=True)),
                ('nom', models.CharField(default='', max_length=155, null=True)),
                ('adresse', models.CharField(default='', max_length=155, null=True)),
                ('num', models.CharField(default='', max_length=255, null=True)),
                ('toiletteur', models.CharField(default='', max_length=255, null=True)),
                ('mail', models.CharField(default='', max_length=255, null=True)),
                ('profession', models.CharField(max_length=155, null=True, unique=True)),
                ('comment', models.CharField(max_length=155, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Chien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(default='', max_length=155, null=True)),
                ('age', models.CharField(default='', max_length=155, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.client')),
            ],
        ),
    ]
