# Generated by Django 3.2.2 on 2021-05-06 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('race', models.CharField(default='', max_length=155, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='client',
            name='comment',
            field=models.CharField(max_length=155, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='profession',
            field=models.CharField(max_length=155, null=True),
        ),
        migrations.AddField(
            model_name='chien',
            name='race',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='management.race'),
        ),
    ]
