# Generated by Django 3.2.3 on 2021-05-17 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_auto_20210513_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='fired',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='joined',
            field=models.DateTimeField(null=True),
        ),
    ]
