# Generated by Django 3.2.2 on 2021-05-06 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_auto_20210506_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chien',
            name='race',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.race'),
        ),
        migrations.AlterField(
            model_name='client',
            name='chien',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.chien'),
        ),
    ]
