# Generated by Django 3.2.2 on 2021-05-06 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_auto_20210506_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='chien',
            name='comment',
            field=models.CharField(default='', max_length=255, null=True),
        ),
    ]
