# Generated by Django 3.2.2 on 2021-05-06 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_chien_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(default='', max_length=255, null=True)),
                ('prix', models.DecimalField(decimal_places=2, default='', max_digits=6, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RDV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('completed', models.DateField()),
                ('client', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.client')),
                ('service', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.service')),
            ],
        ),
    ]
