# Generated by Django 3.2.2 on 2021-05-06 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_rdv_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rdv',
            name='completed',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='rdv',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
