# Generated by Django 3.2.2 on 2021-05-06 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0007_auto_20210506_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rdv',
            name='completed',
            field=models.DateTimeField(null=True),
        ),
    ]
