# Generated by Django 3.2.2 on 2021-05-07 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0010_alter_service_duree'),
    ]

    operations = [
        migrations.AddField(
            model_name='rdv',
            name='comment',
            field=models.TextField(default='', max_length=255, null=True),
        ),
    ]
