# Generated by Django 3.2.2 on 2021-05-07 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0011_rdv_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='rdv',
            name='toiletteur',
            field=models.CharField(default='', max_length=255, null=True),
        ),
    ]
