# Generated by Django 3.2.2 on 2021-05-07 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0013_auto_20210507_1035'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenom', models.CharField(max_length=155, null=True)),
                ('nom', models.CharField(default='', max_length=155, null=True)),
                ('adresse', models.CharField(default='', max_length=155, null=True)),
                ('num', models.CharField(default='', max_length=255, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='client',
            name='toiletteur',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.employee'),
        ),
        migrations.AlterField(
            model_name='rdv',
            name='toiletteur',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.employee'),
        ),
    ]
