# Generated by Django 3.2.3 on 2021-05-29 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(default='', max_length=255, null=True)),
                ('prix', models.DecimalField(decimal_places=2, default='', max_digits=6, null=True)),
                ('race', models.CharField(choices=[('Petite', 'Petit'), ('Moyenne', 'Moyen'), ('Grande', 'Grand')], default='Moyenne', max_length=9)),
                ('duree', models.CharField(choices=[('~ 5 min.', '5'), ('~ 30 min.', '30'), ('~ 1h00', '60'), ('~ 1h30', '90'), ('~ 2h00', '120'), ('~ 2h +', '+120')], default='~ 30 min.', max_length=9)),
            ],
        ),
    ]
