# Generated by Django 3.2.3 on 2021-05-29 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employes', '0001_initial'),
        ('clients', '0001_initial'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RDV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('completed', models.DateTimeField(null=True)),
                ('comment', models.TextField(default='', max_length=255, null=True)),
                ('client', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='clients.client')),
                ('service', models.ManyToManyField(default='', null=True, to='services.Service')),
                ('toiletteur', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='employes.employee')),
            ],
        ),
    ]
