# Generated by Django 3.2.3 on 2021-06-03 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rdv', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rdv',
            name='date',
            field=models.DateTimeField(null=True),
        ),
    ]
